AWSTemplateFormatVersion: "2010-09-09"

Resources:

  ########################################
  # TERRAFORM STATE BUCKET AND LOCK TABLE
  ########################################
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled


  TerraformLockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "tf-state-table"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true


  ########################################
  # Github Oidc Provider
  ########################################
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - ffffffffffffffffffffffffffffffffffffffff


Outputs:

  TerraformStateBucketName:
    Value: !Ref TerraformStateBucket
    Description: Name of terraform state S3 bucket

  TerraformLockTableName:
    Value: !Ref TerraformLockTable
    Description: Name of the DynamoDB lock table

  GithubOidcArn:
    Value: !Ref GithubOidc
    Description: Arn of github oidc provider
