Transform: AWS::Serverless-2016-10-31

Parameters:

  PipelinesAccountId:
    Description: Account id of pipelines account
    Type: String


Resources:

  AssumeAdminPermissionsRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role to be assumed by pipelines account users to deploy resources.
      RoleName: target-account-deployment-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${PipelinesAccountId}:root"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  TargetAccountDeploymentRoleArn:
    Description: Role arn that grants access to the pipelines
    Value: !GetAtt AssumeAdminPermissionsRole.Arn
